#ifndef __Hello_wxFB_GLBaseFrame__
#define __Hello_wxFB_GLBaseFrame__

/**
@file
Subclass of BaseFrame, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing BaseFrame */
class AppFrame : public BaseFrame
{
	protected:
		// Handlers for BaseFrame events.
		void onLoadMeshClicked( wxCommandEvent& event );
		void onIsActiveChecked( wxCommandEvent& event );
		void onSpinCtrlValueChanged( wxSpinEvent& event );
	public:
		/** Constructor */
		AppFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __Hello_wxFB_GLBaseFrame__
